# @format

backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Repository", name: "repository", widget: "string" }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }
